### PR TITLE
Remove custom Str class, use Illuminate instead

### PR DESCRIPTION
**Pull request by ilazaridis**

### CODE REVIEW

**Comment by davideprevosto** [comment]
I also removed the Str class, using the Illuminate one. Is it not the correct way?

**Comment by ilazaridis** [comment]
Yes, it is. I closed it because I already fixed that in my fork.

**Comment by encodiaweb** [comment]
@ilazaridis Why close this PR? It could be merged by a maintainer of this repository... Isn't it?

**Comment by patrickcarlohickman** [comment]
@ilazaridis ,

I appreciate the PR for this. The custom Str class was used to support older versions of Laravel. I ended up updating the package to drop support for Laravel 4.1 - 8.x, so there was a bunch of extra fluff in here that could be removed.

The new 3.0.0 tag for this support was released today. The old 2.1.0 tags will still work if you need Laravel <= 8x or PHP <= 8.0.

Thanks,
Patrick

**Pull request closed without merging**
